### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by martoio** [franklincandanoza/prj-rev-bwfs-tea-cozy#4]
Make sure you add the ``alt`` attribute to your images to maintain accessibility for all audiences of the page (particularly visually-impaired users). Remember to add it even in these simple projects and it will become a habit. (Hint: as long as you have the ``alt`` attribute with something semi-meaningful, we'll be happy with it).
For more info: https://www.codecademy.com/articles/accessibility

https://github.com/franklincandanoza/prj-rev-bwfs-tea-cozy/blob/4a95f739c3f4414d176875a87d007911e3b2db9a/Tea%20Cozy/index.html#L32

**Comment by franklincandanoza** [comment]
thanks for your comment
