### ISSUE TITLE
Extraneous CSS

### ISSUE THREAD

**Issue by martoio** [franklincandanoza/prj-rev-bwfs-tea-cozy#5]
You never really use this CSS, so it would be better to remove it to keep things tidy:

https://github.com/franklincandanoza/prj-rev-bwfs-tea-cozy/blob/4a95f739c3f4414d176875a87d007911e3b2db9a/Tea%20Cozy/resources/css/style.css#L65-L69

**Comment by franklincandanoza** [comment]
done.
